name: Deployment - Resusable Workflow

on: 
  workflow_call:

jobs:
  reuse-deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v3
        with:
          version: v1.26.0
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: '${{ secrets.KUBECONFIG }}'
      - run: kubectl version --short -o yaml
    # Below codes are added to complete the task
      - run: >
          echo "INGRESS_IP=$(kubectl -n ingress-nginx get services
          ingress-nginx-controller -o
          jsonpath='{.status.loadBalancer.ingress[0].ip}')" >> $GITHUB_ENV
      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["kubernetes/development/*.yaml"]'
        env:
          NAMESPACE: '${{ vars.NAMESPACE }}'
          REPLICAS: '${{ vars.REPLICAS }}'
          IMAGE: >-
            ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha
            }}
          INGRESS_IP: '${{ env.INGRESS_IP }}'
      - run: cat kubernetes/development/*.yaml